name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Add gradle PPA
      run : sudo add-apt-repository ppa:cwchien/gradle -y

    - name: Update repositories
      run: sudo apt update 
    
    - name: Install packages
      run: sudo apt install -y cmake ninja-build openjdk-11-jdk wget unzip gradle build-essential git

    - name: Build CMake 3.18.1
      run: git clone https://github.com/Kitware/CMake -b v3.18.1 --depth 1 && cd CMake && ./bootstrap && make -j16 && sudo make install 

    # Setup Android SDK, and auto-accept licenses
    - name: Install Android SDK
      run: wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip && mkdir android-sdk-linux && unzip -qq android-sdk.zip -d android-sdk-linux && export ANDROID_HOME=./android-sdk-linux && echo y | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux --update && (echo y; echo y; echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk-linux --licenses

    # Call SDKManager to install the Android NDK
    - name: Install Android NDK
      run: $GITHUB_WORKSPACE/android-sdk-linux/cmdline-tools/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE/android-sdk-linux --install "ndk;25.1.8937393" --channel=3

    - name: Download dependencies
      shell: bash
      run: cd $GITHUB_WORKSPACE/android/ && wget https://www.satdump.org/android_deps.zip && unzip android_deps.zip -d deps 

    - name: LS
      shell: bash
      run: ls $GITHUB_WORKSPACE/android-sdk-linux/cmdline-tools/

    - name: Build
      shell: bash
      run: export ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk-linux && cd $GITHUB_WORKSPACE/android && gradle assembleDebug

    - name: Re-Build to include plugins
      shell: bash
      run: export ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk-linux && cd $GITHUB_WORKSPACE/android && gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: SatDump-debug.apk
        path: ${{runner.workspace}}/android/app/build/outputs/apk/debug/app-debug.apk